### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by damienalexandre** [mdarse/password-strength-validator#1]
Please tag a release and add this lib to packagist.

Your installation procedure does not work.

**Comment by vctls** [comment]
In the meantime, I've added the repo to my dependencies through Composer like this:

<pre>
    [
      {  
        "url": "https://github.com/mdarse/password-strength-validator.git",  
        "type": "git"
      }
    ],
    "require": {
        "mdarse/password-strength-validator": "dev-master"
    },
</pre>

**Comment by mdarse** [comment]
Just tagged `v1.0.0` and pushed it to [Packagist](https://packagist.org/packages/mdarse/password-strength-validator#v1.0.0) ✨
